apiVersion: v1
kind: Service
metadata:
  name: open-data-service
  namespace: open-data-app
spec:
  selector:
    app: open-data-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer