apiVersion: v1
kind: Service
metadata:
  name: open-data-service
  namespace: open-data-app
spec:
  type: NodePort
  selector:
    app: open-data-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 32325
